#!/usr/bin/env python3
import csv,hashlib,json,re,ssl
from datetime import datetime,timezone
from html import unescape
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urljoin
from urllib.request import Request,urlopen
ROOT=Path(__file__).resolve().parents[1];CFG=json.loads((ROOT/'config'/'sources.json').read_text());NOW=datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00','Z')
class Links(HTMLParser):
 def __init__(self):super().__init__();self.links=[];self.href=None;self.text=[]
 def handle_starttag(self,t,a):
  if t=='a':self.href=dict(a).get('href');self.text=[]
 def handle_data(self,d):
  if self.href is not None:self.text.append(d)
 def handle_endtag(self,t):
  if t=='a' and self.href:self.links.append((self.href,' '.join(' '.join(self.text).split())));self.href=None;self.text=[]
def fetch(u):
 with urlopen(Request(u,headers={'User-Agent':'OTIS-Opportunity-Tracker/1.1 (+https://github.com/SkyGuardDefense/otis-tracker)'}),timeout=25,context=ssl.create_default_context()) as r:return r.status,r.geturl(),r.read(1500000).decode('utf-8',errors='replace')
def tags(matches):
 s=' '.join(matches).lower();out=[]
 for label,terms in {'Counter-UxS':['uas','uxs','drone','counter'],'EO/IR':['optical','eo/ir','electro-optical','infrared'],'Sensor Fusion':['fusion','geometry'],'Autonomy':['autonomy','edge ai','artificial intelligence'],'Unmanned Payload':['payload','unmanned']}.items():
  if any(t in s for t in terms):out.append(label)
 return out or ['OTIS relevance needs review']
def award(channel,text):
 s=(channel+' '+text).lower()
 if 'sbir' in s or 'sttr' in s:return 'SBIR/STTR'
 if 'accelerator' in s:return 'Accelerator / seed funding'
 if 'rfi' in s:return 'RFI / market research'
 if 'diu' in s:return 'Commercial Solutions Opening / unspecified'
 return 'Not published'
def main():
 keys=[k.lower() for k in CFG['keywords']];report={'scannedAt':NOW,'sources':[]};candidates=[]
 for source in CFG['sources']:
  result={'name':source['name'],'channel':source['channel'],'url':source['url'],'checkedAt':NOW}
  try:
   status,final,html=fetch(source['url']);m=re.search(r'<title[^>]*>(.*?)</title>',html,re.I|re.S);result.update({'status':status,'finalUrl':final,'title':re.sub(r'\s+',' ',unescape(m.group(1))).strip() if m else ''});p=Links();p.feed(html);seen=set()
   for href,text in p.links:
    url=urljoin(final,href);matches=sorted({k for k in keys if k in f'{text} {url}'.lower()})
    if matches and url not in seen and url.startswith(('http://','https://')):
     seen.add(url);candidates.append({'source':source['name'],'channel':source['channel'],'sourceUrl':source['url'],'candidateUrl':url,'anchorText':text[:500],'keywordMatches':matches,'checkedAt':NOW,'reviewStatus':'Needs validation'})
   result['candidateCount']=sum(c['source']==source['name'] for c in candidates)
  except Exception as e:result['error']=f'{type(e).__name__}: {e}'
  report['sources'].append(result)
 records=json.loads((ROOT/'data'/'opportunities.json').read_text());by_url={r.get('sourceUrl'):r for r in records if r.get('sourceUrl')};added=updated=0
 for c in candidates:
  url=c['candidateUrl'];existing=by_url.get(url);title=c['anchorText'] or f"{c['source']} candidate";base={'id':'auto-'+hashlib.sha1(url.encode()).hexdigest()[:12],'opportunity':title,'sponsor':c['source'],'channel':c['channel'],'sourceUrl':url,'datePosted':'','deadline':'','awardType':award(c['channel'],title),'otisMatch':tags(c['keywordMatches']),'fitScore':min(5,max(2,2+len(c['keywordMatches'])//2)),'urgency':'MONITOR','status':'Needs validation','nextAction':'Open source, verify opportunity facts and deadline','lastChecked':NOW,'autoGenerated':True,'sourcePage':c['sourceUrl'],'keywordMatches':c['keywordMatches']}
  if existing:
   for k,v in base.items():
    if k in ('lastChecked','keywordMatches','sourcePage','autoGenerated') or not existing.get(k):existing[k]=v
   updated+=1
  else:records.append(base);by_url[url]=base;added+=1
 reports=ROOT/'reports';reports.mkdir(exist_ok=True);report['trackerUpsert']={'added':added,'updated':updated,'totalRecords':len(records)};(reports/'latest-scan.json').write_text(json.dumps(report,indent=2)+'\n');(reports/'candidates.json').write_text(json.dumps(candidates,indent=2)+'\n');(ROOT/'data'/'opportunities.json').write_text(json.dumps(records,indent=2)+'\n')
 fields=['id','opportunity','sponsor','channel','sourceUrl','datePosted','deadline','awardType','otisMatch','fitScore','urgency','status','nextAction','lastChecked']
 with (ROOT/'data'/'opportunities.csv').open('w',newline='') as h:
  w=csv.DictWriter(h,fieldnames=fields);w.writeheader()
  for r in records:
   row={f:r.get(f,'') for f in fields};row['otisMatch']=' | '.join(row['otisMatch']) if isinstance(row['otisMatch'],list) else row['otisMatch'];w.writerow(row)
 print(json.dumps({'scannedAt':NOW,'sources':len(report['sources']),'candidates':len(candidates),'added':added,'updated':updated}))
if __name__=='__main__':main()
