#!/usr/bin/env python3
import json, re, ssl
from datetime import datetime, timezone
from html import unescape
from pathlib import Path
from urllib.parse import urlparse
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
NOW = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')
UA = 'OTIS-Opportunity-Tracker/2.1 (+https://github.com/SkyGuardDefense/otis-tracker)'
NAVIGATION = {'login', 'contact', 'privacy', 'faq', 'faqs', 'overview', 'submission', 'selections', 'about us', 'getting started', 'policy'}
SOCIAL_HOSTS = {'twitter.com', 'x.com', 'linkedin.com', 'facebook.com'}

def clean(value):
    return re.sub(r'\s+', ' ', unescape(value or '')).strip()

def fetch(url):
    request = Request(url, headers={'User-Agent': UA, 'Accept': 'text/html,application/xhtml+xml'})
    with urlopen(request, timeout=25, context=ssl.create_default_context()) as response:
        return response.status, response.geturl(), response.read(1500000).decode('utf-8', errors='replace')

def extract_title(html):
    match = re.search(r'<title[^>]*>(.*?)</title>', html, re.I | re.S)
    return clean(match.group(1)) if match else ''

def extract_labelled_dates(text):
    pattern = r'(?:close|closing|deadline|submit(?:tal|)?(?: by)?|proposal due)[^A-Za-z0-9]{0,40}((?:\d{1,2}[/-]){2}\d{2,4}|(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},?\s+\d{4})'
    return sorted(set(clean(value) for value in re.findall(pattern, text, re.I)))

def validate(record):
    url = record.get('sourceUrl', '')
    host = urlparse(url).netloc.lower().removeprefix('www.')
    title = clean(record.get('opportunity'))
    result = {'id': record.get('id'), 'sourceUrl': url, 'checkedAt': NOW, 'sourceTier': record.get('sourceTier', ''), 'canonicalKey': record.get('canonicalKey', '')}
    if record.get('sourceTier') == 'supplemental':
        result.update({'disposition': 'lead_requires_official_notice', 'verified': False})
        return result
    if host in SOCIAL_HOSTS or title.lower() in NAVIGATION or not url:
        result.update({'disposition': 'non_opportunity_navigation_or_social', 'verified': False})
        return result
    try:
        status, final, html = fetch(url)
        page_title = extract_title(html)
        text = clean(re.sub(r'<[^>]+>', ' ', html))
        topic = re.search(r'\bDON\d{2}[A-Z0-9-]+\b', record.get('canonicalKey', '') + ' ' + title + ' ' + text, re.I)
        result.update({'httpStatus': status, 'finalUrl': final, 'pageTitle': page_title, 'topicId': topic.group(0).upper() if topic else '', 'labelledDates': extract_labelled_dates(text), 'verified': bool(topic), 'disposition': 'official_topic_page' if topic else 'official_page_requires_review'})
    except Exception as error:
        result.update({'verified': False, 'disposition': 'source_unavailable', 'error': f'{type(error).__name__}: {error}'})
    return result

records = json.loads((ROOT / 'data' / 'opportunities.json').read_text())
results = [validate(record) for record in records if record.get('autoGenerated')]
summary = {}
for result in results:
    summary[result['disposition']] = summary.get(result['disposition'], 0) + 1
(ROOT / 'reports' / 'validation.json').write_text(json.dumps({'validatedAt': NOW, 'summary': summary, 'records': results}, indent=2) + '\n')
print(json.dumps({'validatedAt': NOW, 'summary': summary}))
